Denormalize to null if null-like value given
assoconnect/php-date-bundle pull request #7
Opened 2020-06-05 15:04 UTC by TristanPouliquen

2020-06-05 15:13 UTC, fguimier requested changes

2020-06-05 15:13 UTC, fguimier commented on src/Normalizer/AbsoluteDateNormalizer.php
> -            throw new NotNormalizableValueException(self::EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE);
tu peux retourner directement en-dessous  `return '' === $data || null === $data ? null : new AbsoluteDate($data, $format);`

Il faut également que tu enlèves la constante EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE et que tu nettoies les tests unitaires

2020-06-05 15:16 UTC, fguimier commented on src/Normalizer/AbsoluteDateNormalizer.php
> -            throw new NotNormalizableValueException(self::EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE);
Et même en mode maxi-synthétique, supprimer $format
et  `return '' === $data || null === $data ? null : new AbsoluteDate($data, $context[self::FORMAT_KEY] ?? null);`
Mais peuut-être moins lisible donc à toi de toi :)

2020-06-08 15:44 UTC, TristanPouliquen commented on src/Normalizer/AbsoluteDateNormalizer.php
> -            throw new NotNormalizableValueException(self::EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE);
Dans ce cas là on perd le try/catch autour de l'instanciation non ?

J'ai retiré la constante que j'avais oublié en effet.

2020-06-08 17:25 UTC, fguimier commented on src/Normalizer/AbsoluteDateNormalizer.php
> -            throw new NotNormalizableValueException(self::EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE);
la ligne que j'ai mise est à mettre dans le try/catch justement

```
    public function denormalize($data, string $type, string $format = null, array $context = [])
    {
        try {
            return '' === $data || null === $data ? null : new AbsoluteDate($data, $context[self::FORMAT_KEY] ?? null);
        } catch (\Exception $e) {
            throw new NotNormalizableValueException($e->getMessage(), $e->getCode(), $e);
        }
    }
```

2020-06-09 07:38 UTC, fguimier commented on src/Normalizer/AbsoluteDateNormalizer.php
> -            throw new NotNormalizableValueException(self::EMPTY_STRING_OR_NULL_EXCEPTION_MESSAGE);
Il faut également que tu supprimes les tests unitaires liés à cette constante.

Dans AbsoluteDateNormalizerTest

2020-06-09 08:03 UTC, fguimier approved these changes

2020-06-09 15:55 UTC, merged